### PR TITLE
feat(#2300): add logging statements for all errors

### PR DESCRIPTION
**Pull request by kleyow**
Addresses https://github.com/mojaloop/project/issues/2300 ? 

With not much to go on from the story, this is all that I could conceivably imagine as a task for the story. 
Any direction is appreciated.

### CODE REVIEW

**Review by mdebarros — COMMENTED** [review]
I feel like this will print unnecessary errors to the log file.

Should we perhaps only print errors at the "API" (Rest API calls) or "Handler" (Kafka Consumers) application levels?

i.e.
- src/api
- src/handlers

**Comment by kleyow** [comment]
@mdebarros Sounds good to me, reverted some changes. We can always take an incremental approach. Commit push

**Comment by mdebarros** [comment]
> @mdebarros Sounds good to me, reverted some changes. We can always take an incremental approach. Commit pushed.

Thanks! It looks good to me.

There is something else we could change with regard to this PR --> https://github.com/mojaloop/central-ledger/blob/master/src/lib/requestLogger.js

This currently logs all incoming HapiJS requests/responses as debug log entries. I personally feel that it's too verbose to switch these to info since we already have the "audits" for ingress and egress using the Event-SDK.

Let me know your thoughts here.

**Comment by kleyow** [comment]
No strong thoughts. Sounds logical enough for me. I don't have much insight of the pov of a system admin overlooking the central ledger. made the switch to info.

**Comment by lewisdaly** [comment]
> Let me know your thoughts here.

I agree @mdebarros  - yeah having lots of noise on the `info` log entry makes debugging from the command line pretty tricky

**Comment by kleyow** [comment]
I misread your comment. I'm a bit confused. I haven't changed `requestLogger` away from debug in my earlier commits so I feel like I'm missing some context...

**Review by mdebarros — APPROVED** [review]
+1

**Comment by mdebarros** [comment]
> I misread your comment. I'm a bit confused. I haven't changed `requestLogger` away from debug in my earlier commits so I feel like I'm missing some context...

Exactly, you have not changed it. I was raising the question if we should, but after more though I really think we shouldn't. ;)

**Pull request merged**
