### PR TITLE
Add timezone to database connection options set to UTC

### PR DESCRIPTION
**Pull request by noopurj**
https://github.com/mojaloop/project/issues/892

### CODE REVIEW

**Comment by lewisdaly** [comment]
Thanks @noopurj! I'm sorry we missed this one - we have some default reviewers now, so that should alert us when there's some updates.

It looks like the vulnerability check is failing, you probably just need to merge master into your branch and push it again.

**Comment by noopurj** [comment]
> It looks like the vulnerability check is failing, you probably just need to merge master into your branch and push it again.

I have done that, but the checks are now in "Expected — Waiting for status to be reported" not sure how to trigger them?

**Comment by elnyry-sam-k** [comment]
CircleCI is showing this as unauthorized.. @noopurj - can you please follow the recommended forking workflow: https://docs.mojaloop.io/documentation/contributors-guide/standards/creating-new-features.html ?

**Comment by noopurj** [comment]
renamed branch - https://github.com/mojaloop/central-ledger/pull/826

**Pull request closed without merging**
